### ISSUE TITLE
爬虫 出的epg 覆盖的channel 太少

### ISSUE THREAD

**Issue by wnear** [supzhang/epg#15]
爬虫epg的结构， all 分类xml文件：`download/e.xml ` 只有 74个channel，中央和卫视，没有地方台。地方台则只有一个 中国教育2台。

只修改了天数限制，其他未做配置。
依赖安装到 `python main.py`能跑通，似乎有些包没安装，不知道是不是有影响。

**Comment by quanyu98** [comment]
不会设置，epg现在能用，download/e.xml里面全是“精彩节目-暂未提供节目预告信息”gangtai存不了，谁能和来个教程

**Comment by wnear** [comment]
@quanyu

> 不会设置，epg现在能用，download/e.xml里面全是“精彩节目-暂未提供节目预告信息”gangtai存不了，谁能和来个教程

你说的和我说的似乎不是一回事，gangtai的我还没看，epg 也能用，只是自己跑的e.xml 对比51zmt 网站上下载的epg 少太多。

跑了python manage, 看了一下后台，发现channel可以修改、可以新增，也就是修改sqlite 的 channel表、即默认爬虫一开始获取epg用的channel，但这个操作太麻烦了，最佳的效果应该还是解析上传的xml、m3u，一键新增。
