### ISSUE TITLE
翡翠台节目单结束时间异常

### ISSUE THREAD

**Issue by mylittlecatcat** [supzhang/epg#20]
http://epg.51zmt.top:8000/e.xml 中，翡翠台节目单，每个节目的结束时间总是某天的23:59:59，导致无法正常使用。

以今天（2023-05-29）为例：
![image](https://github.com/supzhang/epg/assets/134911049/aeb2f3ea-43fb-4419-8e4e-cbdd4167bb97)

附件是完整的 e.xml ，供参考
[e.xml.zip](https://github.com/supzhang/epg/files/11588920/e.xml.zip)

看了一下代码，tvb爬虫返回的 endtime 总是 None；然后 models.py 有一段处理 endtime 为 None 时赋予 "xxx 23:59:59"，看样子应该是走到这个逻辑了
![image](https://github.com/supzhang/epg/assets/134911049/8ec6e02b-c676-4944-82b1-b92a9b8a8a95)

不过有另一个地方会自动补全 endtime ，似乎没有起作用
![image](https://github.com/supzhang/epg/assets/134911049/8f22d683-63dc-4aef-8993-635e9ffb187d)

最后还是没看出问题在哪，希望作者能修复一下吧，感谢！

**Comment by supzhang** [comment]
这里的代码没有问题，可以正常生成结束时间。只是我自己使用代码，在加入结束时间的地方忘记把mytvsuper来源加上了。现在已经正常。

**Comment by mylittlecatcat** [comment]
正常了，感谢！
