### ISSUE TITLE
香港台来源于mytvsuper的节目无法生成xml文件

### ISSUE THREAD

**Issue by kinshupoon** [supzhang/epg#35]
通过python main.py -n 翡翠台，明珠，无线新闻等，可以显示节目信息，但是通过执行Python main.py时这些台的节目缺没写入xml，请问是这个是什么原因呢

**Comment by hero7069** [comment]
> 通过python main.py -n 翡翠台，明珠，无线新闻等，可以显示节目信息，但是通过执行Python main.py时这些台的节目缺没写入xml，请问是这个是什么原因呢

大佬这个epg应该怎么设置

**Comment by hero7069** [comment]
> 通过python main.py -n 翡翠台，明珠，无线新闻等，可以显示节目信息，但是通过执行Python main.py时这些台的节目缺没写入xml，请问是这个是什么原因呢

参数应该怎么填写，我想抓取凤凰卫视

**Comment by kinshupoon** [comment]
> > 通过python main.py -n 翡翠台，明珠，无线新闻等，可以显示节目信息，但是通过执行Python main.py时这些台的节目缺没写入xml，请问是这个是什么原因呢
> 
> 参数应该怎么填写，我想抓取凤凰卫视
